#!/usr/bin/env bash

. "$(dirname "$0")/_/husky.sh"

if [ "$GIT_NV" = "1" ]; then
  echo "[husky] skipping commit-msg hooks because variable GIT_NV is set to 1"
  exit 0
fi

sh ./.husky/commit-msg-scripts/commitizen.sh

if [ $? -ne 0 ]; then
  echo "[husky] commit validation error"
  exit 1
fi
